services:
  database:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - /home/jose/dev/postgres:/var/lib/postgresql/data
      - /home/jose/dev/nutri-be-ddd-ca/db/create.sql:/var/lib/postgresql/create.sql
      - /home/jose/dev/nutri-be-ddd-ca/db/create_db.sh:/docker-entrypoint-initdb.d/init-database.sh
    environment:
      - POSTGRES_HOST=localhost
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=app
      - POSTGRES_SSL=false
    healthcheck:
      test: pg_isready
      interval: 10s
      timeout: 5s
      retries: 5
