@startuml Use Case

actor Admin

usecase ManageProfilePermission #LightGreen
usecase GrantProfilePermission #LightGreen
usecase RevokeProfilePermission #LightGreen
usecase AssignProfilePermission #LightGreen
usecase UnassignProfilePermission #LightGreen
usecase ListPermissionsByProfile #LightGreen
usecase ManageAccountPermission #LightGreen
usecase GrantAccountPermission #LightGreen
usecase RevokeAccountPermission #LightGreen
usecase AssignAccountPermission #LightGreen
usecase UnassignAccountPermission #LightGreen
usecase ListPermissionsByAccount #LightGreen

Admin -d-> (ManageProfilePermission) 
(ManageProfilePermission) <.d. (GrantProfilePermission) 
(ManageProfilePermission) <.d. (RevokeProfilePermission) 
(ManageProfilePermission) <.d. (AssignProfilePermission) 
(ManageProfilePermission) <.d. (UnassignProfilePermission) 
(ManageProfilePermission) <.d. (ListPermissionsByProfile) 

Admin -u-> (ManageAccountPermission) 
(ManageAccountPermission) <.u. (GrantAccountPermission) 
(ManageAccountPermission) <.u. (RevokeAccountPermission) 
(ManageAccountPermission) <.u. (AssignAccountPermission) 
(ManageAccountPermission) <.u. (UnassignAccountPermission) 
(ManageAccountPermission) <.u. (ListPermissionsByAccount) 

@enduml