@startuml Use Case

actor User
actor Admin

usecase CreateAccount #LightGreen
usecase Login #LightGreen
usecase GetAccount #LightGreen
usecase DeleteAccount #LightGreen
usecase ChangePassword #LightGreen
usecase ManageProfile #LightGreen
usecase ManageFunctionalityType #LightGreen
usecase ManageFunctionality #LightGreen
usecase ManageProfilePermission #LightGreen
usecase ManageAccountPermission #LightGreen
usecase ManageAccount #LightGreen

User <|-r- Admin

User -l-> (CreateAccount) 
User -d-> (DeleteAccount)
User -r-> (GetAccount)
(GetAccount) <.d. (ChangePassword) : extends
User -d-> (Login)

Admin -u-> (ManageProfile) 
Admin -u-> (ManageAccount) 
Admin -d-> (ManageProfilePermission) 
Admin -d-> (ManageAccountPermission) 
Admin -r-> (ManageFunctionality) 
Admin -r-> (ManageFunctionalityType) 

@enduml