@startuml Use Case

actor Admin

usecase ManageAccount #LightGreen
usecase EnableAccount #LightGreen
usecase DisableAccount #LightGreen
usecase DeleteAccount #LightGreen
usecase AssignProfile #LightGreen
usecase UnassignProfile #LightGreen
usecase GetAccount #LightGreen
usecase ResetPassword #LightGreen

Admin --> (ManageAccount) 
(ManageAccount) <.d. (AssignProfile) 
(ManageAccount) <.d. (UnassignProfile) 
(ManageAccount) <.d. (GetAccount) 
(ManageAccount) <.d. (EnableAccount) 
(ManageAccount) <.d. (DisableAccount) 
(ManageAccount) <.l. (DeleteAccount) 
(ManageAccount) <.r. (ResetPassword) 

@enduml