@startuml Use Case

actor Admin

usecase ManageProfilePermission #LightYellow
usecase GrantProfilePermission #LightGray
usecase RevokeProfilePermission #LightGray
usecase AssignProfilePermission #LightGreen
usecase UnassignProfilePermission #LightGreen
usecase GetPermissionByProfile #LightGray
usecase ManageAccountPermission #LightGray
usecase GrantAccountPermission #LightGray
usecase RevokeAccountPermission #LightGray
usecase AssignAccountPermission #LightGray
usecase UnassignAccountPermission #LightGray
usecase GetPermissionByAccount #LightGray

Admin -d-> (ManageProfilePermission) 
(ManageProfilePermission) <.d. (GrantProfilePermission) 
(ManageProfilePermission) <.d. (RevokeProfilePermission) 
(ManageProfilePermission) <.d. (AssignProfilePermission) 
(ManageProfilePermission) <.d. (UnassignProfilePermission) 
(ManageProfilePermission) <.d. (GetPermissionByProfile) 

Admin -u-> (ManageAccountPermission) 
(ManageAccountPermission) <.u. (GrantAccountPermission) 
(ManageAccountPermission) <.u. (RevokeAccountPermission) 
(ManageAccountPermission) <.u. (AssignAccountPermission) 
(ManageAccountPermission) <.u. (UnassignAccountPermission) 
(ManageAccountPermission) <.u. (GetPermissionByAccount) 

@enduml