@startuml Use Case

actor Admin

usecase ManageProfile #LightGreen
usecase CreateProfile #LightGreen
usecase GetProfile #LightGreen
usecase PatchProfile #LightGreen
usecase ListProfile #LightGreen
usecase DeleteProfile #LightGreen
usecase AssignProfile #LightGreen
usecase UnassignProfile #LightGreen

Admin --> (ManageProfile) 
(ManageProfile) <.d. (AssignProfile) 
(ManageProfile) <.d. (UnassignProfile) 
(ManageProfile) <.d. (CreateProfile) 
(ManageProfile) <.d. (PatchProfile) 
(ManageProfile) <.d. (DeleteProfile) 
(ManageProfile) <.d. (ListProfile) 
(ManageProfile) <.d. (GetProfile) 

@enduml