@startuml Use Case

actor Admin

usecase ManagePermission #LightGray
usecase GrantPermission #LightGray
usecase RevokePermission #LightGray
usecase AssignPermission #LightGray
usecase UnassignPermission #LightGray

Admin --> (ManagePermission) 
(ManagePermission) <.d. (GrantPermission) 
(ManagePermission) <.d. (RevokePermission) 
(ManagePermission) <.d. (AssignPermission) 
(ManagePermission) <.d. (UnassignPermission) 

@enduml