@startuml Use Case

actor User
actor Admin

usecase CreateAccount #LightGreen
usecase Login #LightGreen
usecase GetAccount #LightGreen
usecase ChangePassword #LightGreen
usecase CreateProfile #LightGreen
usecase GetProfile #LightGreen
usecase PatchProfile #LightGreen
usecase ListProfile #LightGreen
usecase DeleteProfile #LightGreen
usecase ManageProfile #LightYellow

User <|-r- Admin

User -l-> (CreateAccount) 
User -r-> (GetAccount)
(GetAccount) <.d. (ChangePassword) : extends
User -d-> (Login)

Admin --> (ManageProfile) 
(ManageProfile) <.r. (AssignProfile) 
(ManageProfile) <.r. (CreateProfile) 
(ManageProfile) <.r. (PatchProfile) 
(ManageProfile) <.r. (DeleteProfile) 
(ManageProfile) <.r. (ListProfile) 
(ManageProfile) <.r. (GetProfile) 

Admin -r-> (ManageUser) 
Admin -r-> (ManageApplication) 
Admin -r-> (ManagePermission) 
Admin -r-> (ManageFunctionality) 
Admin -r-> (ManageFunctionalityType) 

@enduml